name: CI

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetches all history for all tags and branches, including submodules
        fetch-depth: 0
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7' # Adjust according to your project needs

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Start Application Server
      run: |
        nohup python3 app.py > server.log 2>&1 &
        echo $! > APP_PID

    - name: Health Check
      run: |
        sleep 10 # Wait for the server to start
        curl --retry 5 --retry-delay 10 --retry-connrefused http://localhost:5000/health -X POST -d '{"status":"ok"}' -H "Content-Type: application/json"
    
    - name: Run Tests
      run: |
        python3 test.py
    
    - name: Cleanup
      if: always()
      run: |
        kill $(cat APP_PID)
